version: "3"
services:
  liner-temperature-scraper:
    build:
      context: .
    image: liner-temperature-scraper:latest
    container_name: liner-temperature-scraper
    working_dir: /app/src
    restart: unless-stopped
    command: [ "python", "main.py" ]
    volumes:
      - /srv/data:/app/data
