version: "3"
services:
  liner-temperature-scraper:
    build:
      context: .
    image: liner-temperature-scraper:latest
    container_name: liner-temperature-scraper
    working_dir: /app
    restart: unless-stopped
    command: [ "python", "src/main.py" ]
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      - /etc/localtime:/etc/localtime:ro # sync timezone with host machine
