[influx2]
    url = "http://gfyvrdatadash:8086"
    token = "ewUzNRITtSXGqLh9Tw5Yk877oS6-rxtqDGbijXgdaLMafcjRgJb-hrgbjm3Rdva0EuGeObnoHnxtYOrRULOJNA=="
    org = "generalfusion"
    timeout = 10_000
    connection_pool_maxsize = 40
    auth_basic = false
    update_period = 3