float:
  top_PID:
    source_time: top_timestamp
    tags:
      type_measure: setpoint
      type_hardware: heater power
      location: upper
  
  bot_PID:
    source_time: bot_timestamp
    tags:
      type_measure: setpoint
      type_hardware: heater power
      location: upper
  
  top_batterylevel:
    source_time: top_timestamp
    tags:
      type_measure: percentage
      type_hardware: battery level
      location: upper
  
  bot_batterylevel:
    source_time: bot_timestamp
    tags:
      type_measure: percentage
      type_hardware: battery level
      location: lower
  
  top_TC1:
    source_time: top_timestamp
    tags:
      type_measure: temperature
      type_hardware: thermocouple
      location: upper, position 1
  
  top_TC2:
    source_time: top_timestamp
    tags:
      type_measure: temperature
      type_hardware: thermocouple
      location: upper, position 2
  
  top_TC3:
    source_time: top_timestamp
    tags:
      type_measure: temperature
      type_hardware: thermocouple
      location: upper, position 3
  
  bot_TC1:
    source_time: bot_timestamp
    tags:
      type_measure: temperature
      type_hardware: thermocouple
      location: lower, position 1  
  
  bot_TC2:
    source_time: bot_timestamp
    tags:
      type_measure: temperature
      type_hardware: thermocouple
      location: lower, position 2  
  
  bot_TC3:
    source_time: bot_timestamp
    tags:
      type_measure: temperature
      type_hardware: thermocouple
      location: lower, position 3  
  
  IR_ref:
    source_time: top_timestamp
    tags:
      type_measure: temperature
      type_hardware: thermocouple
      location: internal to IR sensor
  
  IR_array_temp0:
    source_time: top_timestamp
    tags:
      type_measure: temperature
      type_hardware: infrared
      location: liner bottom +0
  
  IR_array_temp1:
    source_time: top_timestamp
    tags:
      type_measure: temperature
      type_hardware: infrared
      location: liner bottom +1  
  
  IR_array_temp2:
    source_time: top_timestamp
    tags:
      type_measure: temperature
      type_hardware: infrared
      location: liner bottom +2
  
  IR_array_temp3:
    source_time: top_timestamp
    tags:
      type_measure: temperature
      type_hardware: infrared
      location: liner bottom +3
  
  IR_array_temp4:
    source_time: top_timestamp
    tags:
      type_measure: temperature
      type_hardware: infrared
      location: liner bottom +4
  
  IR_array_temp5:
    source_time: top_timestamp
    tags:
      type_measure: temperature
      type_hardware: infrared
      location: liner bottom +5  
  
  IR_array_temp6:
    source_time: top_timestamp
    tags:
      type_measure: temperature
      type_hardware: infrared
      location: liner bottom +6
  
  IR_array_temp7:
    source_time: top_timestamp
    tags:
      type_measure: temperature
      type_hardware: infrared
      location: liner bottom +7
  
  top_setpoint:
    source_time: top_timestamp
    tags:
      type_measure: setpoint
      location: upper
  
  bot_setpoint:
    source_time: bot_timestamp
    tags:
      type_measure: setpoint
      location: lower
  
  upper_pressure_N2:
    source_time: top_timestamp
    source_id: upper_pressure
    tags:
      type_measure: pressure
      type_hardware: stinger
      location: upper
  
  upper_pressure_voltage:
    source_time: top_timestamp
    source_id: upper_pressure_voltage
    tags:
      type_measure: pressure
      type_hardware: stinger
      location: upper

datetime:
  top_timestamp:
  bot_timestamp:

string:
  SD_card_status:
  logging_status:
  top_batwarning:
  bot_batwarning:
  upper_pressure_gastype:
    source_time: top_timestamp
    source_id: gas
    tags:
      type_measure: gas type
      type_hardware: stinger
      location: upper